# Generated by Django 5.1.1 on 2024-11-29 11:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('resposta', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='')),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('tema', models.CharField(max_length=100)),
                ('numero_integrantes', models.IntegerField()),
                ('professor_orientador', models.CharField(blank=True, max_length=100)),
                ('carga_horaria_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dias_reuniao', models.JSONField(blank=True, default=list)),
                ('hora_reuniao', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='')),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('inicio_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('carga_horaria', models.IntegerField(default=0)),
                ('tema', models.CharField(blank=True, max_length=255, null=True)),
                ('periodicidade', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('links', models.URLField(blank=True, max_length=500, null=True)),
                ('link_inscricao', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IniciativaEstudantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='')),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('objetivo', models.TextField(default='Sem objetivo definido', max_length=255)),
                ('docente_supervisor', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255)),
                ('descricao', models.TextField(default='')),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('local', models.CharField(max_length=200)),
                ('inicio_evento', models.DateField(default=django.utils.timezone.now)),
                ('fim_evento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('horario_de_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('horario_de_termino', models.TimeField(default=django.utils.timezone.now)),
                ('palestrante', models.CharField(blank=True, max_length=100)),
                ('opcao_palestrante', models.CharField(choices=[('nome', 'Informar nome'), ('indefinido', 'Indefinido / não informar')], default='indefinido', max_length=10)),
                ('vagas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=10)),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IniciacaoCientifica',
            fields=[
                ('programaoficial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.programaoficial')),
                ('duracao', models.DurationField()),
                ('professor_orientador', models.CharField(max_length=100)),
                ('bolsa_pesquisa', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('apps.programaoficial',),
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('programaoficial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.programaoficial')),
                ('professor_orientador', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('cadeiras_requeridas', models.JSONField(blank=True, default=list)),
                ('requisitos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('apps.programaoficial',),
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('programaoficial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apps.programaoficial')),
                ('local_trabalho', models.CharField(max_length=100)),
                ('organizacao_parceira', models.CharField(max_length=100)),
                ('habilidades_requeridas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('apps.programaoficial',),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
