# Generated by Django 5.1.1 on 2024-10-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('inicio_evento', models.DateTimeField()),
                ('fim_evento', models.DateTimeField()),
                ('vagas', models.IntegerField()),
                ('tipo', models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], max_length=10)),
                ('carga_horaria', models.DecimalField(decimal_places=2, max_digits=5)),
                ('local', models.CharField(max_length=200)),
            ],
        ),
    ]
