# Generated by Django 5.1.1 on 2024-10-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_perfil_email_alter_perfil_trocar_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tema', models.CharField(max_length=100)),
                ('numero_integrantes', models.IntegerField()),
                ('descricao', models.TextField()),
                ('professor_orientador', models.CharField(max_length=100)),
                ('carga_horaria_semanal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dias_reuniao', models.CharField(max_length=100)),
                ('hora_reuniao', models.TimeField()),
            ],
        ),
    ]
