# Generated by Django 5.1.1 on 2024-10-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_grupoestudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tipo_evento',
        ),
    ]
