# Generated by Django 5.1.1 on 2024-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_evento_tipo_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curso',
            field=models.CharField(choices=[('design', 'Design'), ('ciencias da computacao', 'Ciências da Computação'), ('sistemas de informacao', 'Sistemas de Informação'), ('analise e desenvolvimento de sistemas', 'Análise e Desenvolvimento de Sistemas'), ('gestao de tecnologia da informacao', 'Gestão de Tecnologia da Informação')], max_length=50, null=True),
        ),
    ]
