# Generated by Django 5.1.1 on 2024-10-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_perfil_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_de_inicio',
            field=models.DateTimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horario_de_termino',
            field=models.DateTimeField(default='00:00'),
        ),
    ]
