# Generated by Django 5.1.1 on 2024-10-15 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_evento_carga_horaria_evento_horario_de_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fim_evento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_de_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_de_termino',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='inicio_evento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
