# Generated by Django 5.1.1 on 2024-10-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_evento_fim_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='opcaoNome',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
