# Generated by Django 5.1.1 on 2024-10-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_evento_opcaonome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='opcaoNome',
        ),
    ]
