# Generated by Django 5.1.1 on 2024-11-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_evento_opcao_palestrante_evento_palestrante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
