# Generated by Django 5.1.1 on 2024-11-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_remove_perfil_username_perfil_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
