# Generated by Django 5.1.1 on 2024-11-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_perfil_is_staff_perfil_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
