# Generated by Django 5.1.1 on 2024-11-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_perfil_groups_perfil_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
