# Generated by Django 5.1.1 on 2024-11-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_perfil_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
