# Generated by Django 5.1.1 on 2024-11-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_remove_perfil_groups_remove_perfil_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
