# Generated by Django 5.1.1 on 2024-11-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_evento_tags_alter_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fim_evento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
