# Generated by Django 5.1.1 on 2024-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_evento_fim_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='status_inscricoes',
            field=models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10, verbose_name='Status das Inscrições'),
        ),
    ]
