# Generated by Django 5.1.1 on 2024-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_evento_status_inscricoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status_inscricoes',
            field=models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10),
        ),
    ]
