# Generated by Django 5.1.1 on 2024-11-06 09:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_evento_status_inscricoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IniciacaoCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('inicio_evento', models.DateField(default=django.utils.timezone.now)),
                ('fim_evento', models.DateField(blank=True, null=True)),
                ('carga_horaria', models.IntegerField()),
                ('link_inscricao', models.URLField()),
                ('duracao', models.DurationField()),
                ('professor_orientador', models.CharField(max_length=100)),
                ('bolsa_pesquisa', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('inicio_evento', models.DateField(default=django.utils.timezone.now)),
                ('fim_evento', models.DateField(blank=True, null=True)),
                ('carga_horaria', models.IntegerField()),
                ('link_inscricao', models.URLField()),
                ('professor_orientador', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=100)),
                ('cadeiras_requeridas', models.JSONField(blank=True, default=list)),
                ('requisitos', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status_inscricoes', models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('inicio_evento', models.DateField(default=django.utils.timezone.now)),
                ('fim_evento', models.DateField(blank=True, null=True)),
                ('carga_horaria', models.IntegerField()),
                ('link_inscricao', models.URLField()),
                ('local_trabalho', models.CharField(max_length=100)),
                ('organizacao_parceira', models.CharField(max_length=100)),
                ('habilidades_requeridas', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
