# Generated by Django 5.1.1 on 2024-11-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_iniciacaocientifica_monitoria_voluntariado'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoestudo',
            name='status_inscricoes',
            field=models.CharField(choices=[('abertas', 'Abertas'), ('em_breve', 'Abrem em breve'), ('fechadas', 'Fechadas')], default='fechadas', max_length=10),
        ),
        migrations.AddField(
            model_name='grupoestudo',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
