# Generated by Django 5.1.1 on 2024-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_grupoestudo_status_inscricoes_grupoestudo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudo',
            name='dias_reuniao',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
