# Generated by Django 5.1.1 on 2024-11-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_alter_grupoestudo_dias_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudo',
            name='dias_reuniao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
