# Generated by Django 5.1.1 on 2024-11-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_alter_grupoestudo_dias_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoestudo',
            name='dias_reuniao',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
