# Generated by Django 5.1.1 on 2024-11-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_remove_perfil_curso_remove_perfil_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='trocar_perfil',
            field=models.BooleanField(default=False),
        ),
    ]
