# Generated by Django 5.1.1 on 2024-11-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_perfil_trocar_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='trocar_perfil',
        ),
    ]
