# Generated by Django 5.1.1 on 2024-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0030_perfil_trocar_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="IniciativaEstudantil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("responsavel", models.CharField(max_length=255)),
                ("site", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
