# Generated by Django 5.1.1 on 2024-11-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_iniciativaestudantil'),
        ('apps', '0031_remove_perfil_trocar_perfil'),
    ]

    operations = [
    ]
