# Generated by Django 5.1.1 on 2024-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_merge_20241128_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
