# Generated by Django 5.1.1 on 2024-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0035_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("tema", models.CharField(max_length=255)),
                ("periodicidade", models.CharField(max_length=100)),
                ("responsavel", models.CharField(max_length=255)),
                ("links", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
