# Generated by Django 5.1.1 on 2024-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0036_programa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iniciativaestudantil",
            old_name="nome",
            new_name="docente_supervisor",
        ),
        migrations.RemoveField(
            model_name="iniciativaestudantil",
            name="atualizado_em",
        ),
        migrations.RemoveField(
            model_name="iniciativaestudantil",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="iniciativaestudantil",
            name="responsavel",
        ),
        migrations.AddField(
            model_name="iniciativaestudantil",
            name="objetivo",
            field=models.TextField(default="Sem objetivo definido", max_length=255),
        ),
        migrations.AddField(
            model_name="iniciativaestudantil",
            name="status_inscricoes",
            field=models.CharField(
                choices=[
                    ("abertas", "Abertas"),
                    ("em_breve", "Abrem em breve"),
                    ("fechadas", "Fechadas"),
                ],
                default="fechadas",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="iniciativaestudantil",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="iniciativaestudantil",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
        migrations.AlterField(
            model_name="evento",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
        migrations.AlterField(
            model_name="grupoestudo",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="grupoestudo",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
        migrations.AlterField(
            model_name="iniciativaestudantil",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="descricao",
            field=models.TextField(default="Não especificado"),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="titulo",
            field=models.CharField(default="Título não especificado", max_length=255),
        ),
    ]
