# Generated by Django 5.1.1 on 2024-11-28 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0037_rename_nome_iniciativaestudantil_docente_supervisor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Programa",
        ),
        migrations.AddField(
            model_name="iniciacaocientifica",
            name="links",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="iniciacaocientifica",
            name="periodicidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="iniciacaocientifica",
            name="responsavel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iniciacaocientifica",
            name="tema",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="links",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="periodicidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="responsavel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monitoria",
            name="tema",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="links",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="periodicidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="responsavel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="voluntariado",
            name="tema",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fim_evento",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="carga_horaria",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="fim_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="inicio_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="iniciacaocientifica",
            name="link_inscricao",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="carga_horaria",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="fim_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="inicio_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="monitoria",
            name="link_inscricao",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="carga_horaria",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="fim_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="inicio_evento",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="voluntariado",
            name="link_inscricao",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
