# Generated by Django 5.1.1 on 2024-11-29 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_delete_programa_iniciacaocientifica_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.AddField(
            model_name='evento',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
    ]
