# Generated by Django 5.1.1 on 2024-11-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_remove_evento_participantes_evento_participantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='grupoestudo',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='grupoestudo',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='iniciacaocientifica',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='iniciacaocientifica',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='iniciativaestudantil',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='iniciativaestudantil',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='titulo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
