# Generated by Django 5.1.1 on 2024-11-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_alter_evento_descricao_alter_evento_titulo_and_more'),
        ('apps', '0039_remove_evento_participantes_evento_participantes'),
    ]

    operations = [
    ]
